#' Get Receiver Type
#'
#' This function takes a list of file paths to raw acoustic receiver detection
#' files supplied by the user and identifies the type of acoustic receiver
#' technology (Lotek, ATS, Teknologic) used to generate the file.
#'
#' @param file_list A vector of raw acoustic detection file paths
#' @return A dataframe containing the file path, file name, and technology type
#' @export
get_receiver_type <- function(file_list){
  receiver_type_list <- data.frame(file_name = rep(NA, length(file_list)),
                                   Name = rep(NA, length(file_list)),
                                   file_type = rep(NA, length(file_list)))
  for (i in 1:length(file_list)){
    file_name <- file_list[i]
    receiver_type_list$file_name[i] <- file_name
    receiver_type_list$Name <- Filename <- stringr::str_split(file_name, pattern = '\\.')[[1]][1]
    receiver_type_list$file_type[i] <- ifelse(stringr::str_detect(file_name,'L'),
                                              "Lotek",
                                              ifelse(stringr::str_detect(file_name,'.SUM'),
                                                     "Teknologic",
                                                     "ATS"))
  }
  receiver_type_list
}

#' Read a Lotek Acoustic Receiver File
#'
#' This function takes a raw acoustic detection file generated by a Lotek
#' JSATS receiver and processes it into a dataframe which can be used by
#' the filtering functions in this package.This is called within read_jsats().
#'
#' @param path the path to the folder containing the desired file
#' @param file the path of the desired file
#' @param timezone the Olsen Named time zone, default is "America/Los_Angeles"
#' @return A dataframe converting the raw detection data into rows of detections
#' @export
read_lotek <- function(path, file, timezone="America/Los_Angeles"){
  LOT = read.csv(file.path(path,file),
                 colClasses = c(character(),
                                numeric(),
                                numeric(),
                                character(),
                                numeric()),
                 col.names = c("ReceiverSN","DateTime_Local","FS","Tag_Decimal","Tag_Hex","P"),
                 skip = 0)
  LOT$ReceiverSN <- as.numeric(gsub("WHS4K-","",LOT$ReceiverSN)) #Turn the file name into serial
  LOT$DateTime_Local =  as.POSIXct(LOT$DateTime_Local, #Convert serial DateTime to real DT
                       tz = timezone,
                       origin = "1899-12-30")
  LOT$FS = lubridate::seconds(LOT$FS) #Convert fractional seconds from number to seconds
  LOT$DateTime_Local = LOT$DateTime_Local+LOT$FS #Add them together
  LOT$Filename = stringr::str_split(file, pattern = '\\.')[[1]][1]
  LOT$Make = rep("Lotek", length(LOT$DateTime_Local))
  LOT
}

#' Read a Teknologic Acoustic Receiver File
#'
#' This function takes a raw acoustic detection file generated by a Teknologic
#' JSATS receiver and processes it into a dataframe which can be used by
#' the filtering functions in this package. This is called within read_jsats().
#'
#' @param path the path to the folder containing the desired file
#' @param file the path of the desired file
#' @param timezone the Olsen Named time zone, default is "America/Los_Angeles"
#' @return A dataframe converting the raw detection data into rows of detections
#' @export
read_tekno <- function(path, file, timezone="America/Los_Angeles"){

  TEK <- read.csv(file.path(path,file),
                  colClasses = c(character(),character(),character(),
                                 character(),numeric(),numeric(),
                                 numeric(), numeric(), numeric(),
                                 numeric(), numeric(), numeric(),
                                 numeric(), logical()),
                  skip = 8,
                  header = TRUE)

  TEK$Tag_Hex = as.character(substr(TEK$TagCode,4,7)) #Extract hex format of tag code
  TEK <- TEK[TEK$valid == 1,] # filter out "invalid" detections X = 0
  TEK$ReceiverSN <- gsub("-","",TEK$Serial.Number) #Retrieve Serial Number
  TEK$Tag_Decimal = broman::hex2dec(TEK$Tag_Hex) # Convert hex to dec format
  TEK$DateTime_Local = lubridate::mdy_hms(TEK$Date.Time, tz = timezone)
  TEK$Volt = TEK$vBatt
  TEK$Freq = 416.666 + (TEK$Freq/1000)
  TEK$Thres = TEK$Thresh
  TEK$SigStr = TEK$snr
  TEK$Make = rep("Tekno", length(TEK$DateTime_Local))
  TEK

}

#' Read an ATS Acoustic Receiver File
#'
#' This function takes a raw acoustic detection file generated by an ATS JSATS
#' receiver and processes it into a dataframe which can be used by the filtering
#' functions in this package.This is called within read_jsats().
#'
#' @param path the path to the folder containing the desired file
#' @param file the path of the desired file
#' @param timezone the Olsen Named time zone, default is "America/Los_Angeles"
#' @return A dataframe converting the raw detection data into rows of detections
#' @export
read_ats <- function(path, file, timezone="America/Los_Angeles"){
  ATS <- data.frame(read.delim(file = file.path(path,file),
                               skip = 0))
  colnames(ATS) <- "lines"
  ATS$G72 = grepl("G72",ATS$lines)
  ATS$commas = lengths(regmatches(ATS$lines, gregexpr(",",ATS$lines)))
  ATS$valid = ifelse(ATS$G72 == TRUE & ATS$commas == 13, TRUE, FALSE)
  ATS <- ATS[ATS$valid == TRUE,]
  ATS <- tidyr::separate(data = ATS,
                         col = lines,
                         sep = ",",
                         into = c(NA,NA,NA,NA,'DateTime','TagCode',
                                  'Tilt', 'VBatt', 'Temp', 'Pressure',
                                  'SigStr', 'Bit_Period', 'Threshold'))
  ATS$DT_Check = grepl('\\.',ATS$DateTime)
  ATS <- ATS[ATS$DT_Check == TRUE,]
  ATS$DateTime_Local = lubridate::mdy_hms(ATS$DateTime, tz = timezone)
  ATS$FullID = ATS$TagCode
  ATS$Tag_Hex = as.character(substr(ATS$TagCode,5,8)) #There's a space before the G
  ATS$Tag_Decimal = broman::hex2dec(ATS$Tag_Hex)
  ATS$Tilt = as.numeric(ATS$Tilt)
  ATS$Volt = as.numeric(ATS$VBatt)
  ATS$Temp = as.numeric(ATS$Temp)
  ATS$SigStr = as.numeric(ATS$SigStr)
  ATS$BitPer = ATS$Bit_Period
  ATS <- tidyr::separate(data = ATS,
                         col = BitPer,
                         into = c(NA,"B1","B2"),
                         sep = "\\s")
  ATS <- tidyr::separate(data = ATS,
                         col = B2,
                         into = c("B3","B4"),
                         sep = c("/",","))
  ATS$Freq = ifelse(is.na(ATS$B3),-999, 100000/(as.numeric(ATS$B1)+(as.numeric(ATS$B3)/31)))
  ATS$Thres = ifelse(is.na(ATS$B3), -999, as.numeric(ATS$Threshold))
  ReceiverSN <-  gsub("SR","",stringr::str_split(file, pattern = '\\.')[[1]][1])
  ReceiverSN <- stringr::str_split(ReceiverSN,pattern = '_')[[1]][1]
  ATS$ReceiverSN <- rep(ReceiverSN, length(ATS$DateTime_Local))
  ATS$Make <- rep("ATS", length(ATS$DateTime_Local))
  ATS
}

#' Read an Acoustic Receiver File
#'
#' This function takes a raw acoustic detection file generated by a Lotek,
#' Teknologic, or ATS JSATS receiver and determines which reader function to use
#' to process it into a dataframe which can be used by the filtering functions
#' in this package.
#'
#' @param path the path to the folder containing the desired file
#' @param file the path of the desired file
#' @param timezone the Olsen Named time zone, default is "America/Los_Angeles"
#' @return A dataframe converting the raw detection data into rows of detections
#' @export
read_jsats <- function(path, file, timezone="America/Los_Angeles"){
  # file_name <- stringr::str_split(file, pattern = '\\.')[[1]][1]
  file_type <- ifelse(stringr::str_detect(file,'L'),
                      "Lotek",
                      ifelse(stringr::str_detect(file,'.SUM'),
                             "Teknologic",
                             "ATS"))
  ifelse(!(file_type %in% c("Lotek","Teknologic","ATS")),
         {jsats_file <- data.frame()},
         ifelse(file_type == "Lotek",{jsats_file <- read_lotek(path,
                                                               file,
                                                               timezone)},
                ifelse(file_type == "Teknologic",{jsats_file <- read_tekno(path,
                                                                  file,
                                                                  timezone)},
                       ifelse(file_type == "ATS", {jsats_file <- read_ats(path,
                                                           file,
                                                           timezone)},
                              {print("Error")}))))
  jsats_file
}
